name: '#YTN'
favicon: null
layout_spectrum: 0.75
typography_spectrum: 0.6831872486509383
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#020003'
    - '#d4cfcc'
    - '#363437'
    - '#a09b98'
    - '#bb7600'
  brandStrength: 0
  lightness: 0.12156064785085618
  saturation: 0.5786378493066877
  rhythmicContrast: 0.7060216499958187
purpose: []
