name: '#YTN'
favicon: null
layout_spectrum: 0.5
typography_spectrum: 0.6831872486509383
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#020003'
    - '#d4cfcc'
    - '#363437'
    - '#a09b98'
    - '#bb7600'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.0625
  rhythmicContrast: 1
purpose: []
